# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


evenSum = 0
prevFibNum = 1
fibNum = 2
while(fibNum < 4000000):
    print('Current fibonacci number: ' + str(fibNum))
    if(fibNum % 2 == 0):
        evenSum += fibNum
    
    # Three card switch
    nextFibNum = prevFibNum + fibNum
    prevFibNum = fibNum
    fibNum = nextFibNum

print(evenSum)
